"""Add feedback columns to ChatMessage

Revision ID: 04bc12828470
Revises: 59fbd5f01963
Create Date: 2026-05-17 17:06:08.765059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bc12828470'
down_revision: Union[str, Sequence[str], None] = '59fbd5f01963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_correction', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback_notes')
    op.drop_column('chat_messages', 'feedback_correction')
    op.drop_column('chat_messages', 'feedback_rating')
    # ### end Alembic commands ###
