"""Add AgentRun and replace agent_id with agent_run_id

Revision ID: 9a024a86ae7a
Revises: e65dccf855d1
Create Date: 2026-05-15 16:36:12.460582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a024a86ae7a'
down_revision: Union[str, Sequence[str], None] = 'e65dccf855d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('agent_run_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('chat_messages_agent_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_messages', 'agent_id')
    op.drop_constraint(op.f('chat_sessions_agent_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_sessions_agent_id_fkey'), 'chat_sessions', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.add_column('chat_messages', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_agent_id_fkey'), 'chat_messages', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_messages', 'agent_run_id')
    # ### end Alembic commands ###
