"""Add RLAIF columns to ChatMessage

Revision ID: b9af27fc75ef
Revises: 04bc12828470
Create Date: 2026-05-17 17:48:19.374114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9af27fc75ef'
down_revision: Union[str, Sequence[str], None] = '04bc12828470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('rlaif_rating', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('rlaif_critique', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('rlaif_correction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'rlaif_correction')
    op.drop_column('chat_messages', 'rlaif_critique')
    op.drop_column('chat_messages', 'rlaif_rating')
    # ### end Alembic commands ###
