"""Add agent_id to ChatSession

Revision ID: db0d62c4303c
Revises: c64e59ac824d
Create Date: 2026-05-15 16:27:11.068688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0d62c4303c'
down_revision: Union[str, Sequence[str], None] = 'c64e59ac824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'agent_id')
    # ### end Alembic commands ###
