"""Add agent tracking to ChatMessage

Revision ID: e65dccf855d1
Revises: db0d62c4303c
Create Date: 2026-05-15 16:30:19.288549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65dccf855d1'
down_revision: Union[str, Sequence[str], None] = 'db0d62c4303c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('agent_step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'agent_steps', ['agent_step_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_messages', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'agent_step_id')
    op.drop_column('chat_messages', 'agent_id')
    # ### end Alembic commands ###
